# 一、ndarray
## 1.ndarray的特性
### 多维性

In [2]:
import numpy as np

In [21]:
arr = np.array(5) #创建0维的ndarray数组
print (arr)
print("arr的维度：",arr.ndim) #数组的维度number of dimensions

5
arr的维度： 0


In [14]:
arr = np.array([1,2,3]) #创建1维的ndarray数组
print (arr)
print("arr的维度：",arr.ndim) #数组的维度number of dimensions

[1 2 3]
arr的维度： 1


In [15]:
arr = np.array([[1,2,3],[4,5,6]]) #创建2维的ndarray数组
print (arr)
print("arr的维度：",arr.ndim) #数组的维度number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度： 2


# 同质性

In [17]:
arr = np.array([1,'hello']) #不同的数据类型会被强制转换成相同的数据类型
print (arr)

['1' 'hello']


In [20]:
arr = np.array([1,2.5]) #不同的数据类型会被强制转换成相同的数据类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [48]:
arr = np.array(1)
print(arr)
print('数组的形状',arr.shape)
print('数组的维度',arr.ndim)
print('数组元素个数',arr.size)
print('数组元素的数据类型',arr.dtype)
print('元素的转置',arr.T)
print('单个元素占用内存字节数',arr.itemsize)
print('数组总内存占用量:',arr.nbytes)
print('数组内存存储方式:',arr.flags)

1
数组的形状 ()
数组的维度 0
数组元素个数 1
数组元素的数据类型 int64
元素的转置 1
单个元素占用内存字节数 8
数组总内存占用量: 8
数组内存存储方式:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [49]:
arr = np.array([1,2.5,3])
print(arr)
print('数组的形状',arr.shape)
print('数组的维度',arr.ndim)
print('数组元素个数',arr.size)
print('数组元素的数据类型',arr.dtype)
print('元素的转置',arr.T)
print('单个元素占用内存字节数',arr.itemsize)
print('数组总内存占用量:',arr.nbytes)
print('数组内存存储方式:',arr.flags)

[1.  2.5 3. ]
数组的形状 (3,)
数组的维度 1
数组元素个数 3
数组元素的数据类型 float64
元素的转置 [1.  2.5 3. ]
单个元素占用内存字节数 8
数组总内存占用量: 24
数组内存存储方式:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [50]:
arr = np.array([[2,3,4],[4,5,6]])
print(arr)
print('数组的形状',arr.shape)
print('数组的维度',arr.ndim)
print('数组元素个数',arr.size)
print('数组元素的数据类型',arr.dtype)
print('元素的转置',arr.T)
print('单个元素占用内存字节数',arr.itemsize)
print('数组总内存占用量:',arr.nbytes)
print('数组内存存储方式:',arr.flags)

[[2 3 4]
 [4 5 6]]
数组的形状 (2, 3)
数组的维度 2
数组元素个数 6
数组元素的数据类型 int64
元素的转置 [[2 4]
 [3 5]
 [4 6]]
单个元素占用内存字节数 8
数组总内存占用量: 48
数组内存存储方式:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndarray的创建

In [55]:
# 基础的创建方法
list1 = [4,5,6]
arr = np.array(list1,dtype = np.float64)#方法是后面带小括号的，要进行一些具体的操作,array方法中小括号中传入的参数为列表
print(arr.ndim) #属性
print(arr)

1
[4. 5. 6.]


In [57]:
#copy
arr1 = np.copy(arr) # arr1元素跟原始的数组相同，但不是一个数组
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [62]:
#预定义形状
#全0 全1 未初始化 固定值
#全0
arr = np.zeros((2,3),dtype = int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [65]:
arr = np.zeros((200,),dtype = int)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [67]:
#全1
arr = np.ones((5,8),dtype = int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [71]:
#未初始化
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [73]:
arr = np.empty((4,3))
print(arr)

[[1.29157748e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.78020168e-306 4.18412319e-062]
 [7.31382804e+169 9.96276717e-047 1.63138880e+185]
 [9.28162190e-072 3.11049257e-032 6.16945294e-062]]


In [75]:
#固定值
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [78]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [84]:
#等差数列 1 2 3 4 5 / 2 4 6 8
arr = np.arange(1,51,1)#start,end,step(步长)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [91]:
#等间隔数列
arr = np.linspace(0,100,5,dtype = int)#start,end,number of list
print(arr)
arr = np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [94]:
#对数间隔数列
arr = np.logspace(0,10,25,base = 2)#start,end,number of list, 每个均分数的幂次
print(arr)
arr = np.logspace(0,4,3,base = 2)#start,end,number of list, 每个均分数的幂次
print(arr)

[1.00000000e+00 1.33483985e+00 1.78179744e+00 2.37841423e+00
 3.17480210e+00 4.23785238e+00 5.65685425e+00 7.55099450e+00
 1.00793684e+01 1.34543426e+01 1.79593928e+01 2.39729132e+01
 3.20000000e+01 4.27148753e+01 5.70175180e+01 7.61092554e+01
 1.01593667e+02 1.35611276e+02 1.81019336e+02 2.41631824e+02
 3.22539789e+02 4.30538965e+02 5.74700569e+02 7.67133223e+02
 1.02400000e+03]
[ 1.  4. 16.]


In [96]:
arr = np.logspace(0,4,3,base = 3)#start,end,number of list, 每个均分数的幂次
print(arr)

[ 1.  9. 81.]


In [99]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其他数字为0
arr = np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [103]:
# 对角矩阵：主对角线上非0的数字，其他数字为0
arr = np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [107]:
#随机数组的生成
#生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.75720072 0.34415573 0.12348105]
 [0.82652544 0.70364805 0.19338602]]


In [109]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[5.41359484 5.02099478 3.8044302 ]
 [3.0868809  5.24101965 3.11180609]]


In [111]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3,30,(2,3))
print(arr)

[[14 13 29]
 [ 4 17 25]]


In [116]:
# 生成随机浮点数（正态分布）(大部分在-3~3之间)
#期望为0，方差为1
arr = np.random.randn(2,3)
print(arr)

[[ 1.49621627  0.08453238  0.83849044]
 [-2.30960471  0.39064182 -0.42270868]]


In [124]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4. ndarray的数据类型

布尔类型 bool

整数类型 int uint

浮点数 float

复数 complex

In [132]:
arr = np.array([1,0,1,0],dtype='bool')
print(arr)
arr = np.array([1,0,127,0],dtype='int8')
print(arr)

[ True False  True False]
[  1   0 127   0]


## 5.索引与切片

In [5]:
#一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)

[66 49 94 73 22 21 61 36 62 13 91  6 92 59 77 84 46 75 91 21]


In [10]:
print(arr[10])
print(arr[:])#获取全部的数据
print(arr[2:5])#获取0、1、2、3、4、5...中的2~4的元素，左包右不包 (start:end+1)
print(arr[slice(2,15,3)]) #slice(start,end,step)
print(arr[arr>10])# 布尔索引
print(arr[(arr>10) & (arr<70)])# 布尔索引

91
[66 49 94 73 22 21 61 36 62 13 91  6 92 59 77 84 46 75 91 21]
[94 73 22]
[94 21 62  6 77]
[66 49 94 73 22 21 61 36 62 13 91 92 59 77 84 46 75 91 21]
[66 49 22 21 61 36 62 13 59 46 21]


In [13]:
#二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[82 40 52 62 29 21  9 44]
 [ 2 82 45 25  1 39 71 97]
 [49 81 60 63 25 42 82 75]
 [42  6 82 89 96 47 21 73]]


In [28]:
print(arr[3,4]) #索引
print(arr[1:3,:])
print(arr[1,2:5])
print(arr[arr>50])#布尔索引
print(arr[2][arr[2]>50])
print(arr[:,3])

96
[[ 2 82 45 25  1 39 71 97]
 [49 81 60 63 25 42 82 75]]
[45 25  1]
[82 52 62 82 71 97 81 60 63 82 75 82 89 96 73]
[81 60 63 82 75]
[62 25 63 89]


## 6.ndarray的运算

In [39]:
# 算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [40]:
c = [1,2,3]
d = [4,5,6]
print(c+d)
for i in range(len(c)):
    d[i] = d[i]+c[i]
print(d)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [47]:
#数组与标量之间的算术运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3)
print(a*3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [51]:
# 广播机制:1.获取形状 2.是否可以广播
#同一维度：相同、1
a = np.array([1,2,3]) #1*3
b = np.array([[4],[5],[6]]) # 3*1
print(a+b)
print(b - a)
'''
a
1 2 3
1 2 3
1 2 3

b
4 4 4
5 5 5
6 6 6
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


'\na\n1 2 3\n1 2 3\n1 2 3\n\nb\n4 4 4\n5 5 5\n6 6 6\n'

In [53]:
a = np.array([1,2,3]) #1*3
b = np.array([1,2]) # 1*2
print(b-a)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [55]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a*b)
'''
a
1 2 3
4 5 6
7 8 9

b
4 5 6
7 8 9
1 2 3
'''
# 矩阵乘法与上面的print（为算术乘法）不同
print(a@b)

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 2.3 numpy中的常用函数
## 1.基本数学函数

In [59]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [73]:
# 计算指数 e^x
print(np.exp(0))

1.0


In [72]:
# 计算自然对数 lnx
print(np.log(2.71))

0.9969486348916096


In [76]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [78]:
# 计算绝对值
arr = np.array([1,-1,3,-7])
print(np.abs(arr))

[1 1 3 7]


In [81]:
# 计算a的b次幂
print(np.power(arr,3))

[   1   -1   27 -343]


In [84]:
# 四舍五入
print(np.round([3.2,4.57,8.1,9.6]))

[ 3.  5.  8. 10.]


In [86]:
#向上取整，向下取整
arr = np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [90]:
# 检测缺失值(NaN)
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

## 2.统计函数
求和、计算平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累计和、累计差

In [93]:
arr = np.random.randint(1,20,8)
print(arr)

[ 9  5 15  2 16 17  1 10]


In [96]:
#求和
print(np.sum(arr))
print(np.sum([1,2,3]))

75
6


In [98]:
# 计算平均值
print(np.mean(arr))

9.375


In [101]:
# 计算中位数   
print(np.median([1,2,4]))
print(np.median([1,2,4,88]))

2.0
3.0


In [109]:
# 计算标准差、方差
arr1 = np.array([1,2,1,2,1,1,2,1])
arr2 = np.array([1,0,3,0,0,4,2,1])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))#方差
print(np.var(arr2))#方差
print(np.std(arr1))#标准差
print(np.std(arr2))#标准差
print(np.var(arr))#方差
print(np.std(arr))#标准差

1.375
1.375
0.234375
1.984375
0.4841229182759271
1.4086784586980805
34.734375
5.893587617063142


In [114]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))#最大值数，最大值位置
print(np.min(arr), np.argmin(arr))#最小值数，最小值位置

[ 9  5 15  2 16 17  1 10]
17 5
1 6


In [126]:
#分位数
#中位数
#___________
#1  2  3  4
#1    2    3
print(np.median([1,2,3]))
print(np.median([1,2,3,4]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
#_____________
#44  47  64  67
#(47+64)/2
print(np.median(arr))
print(np.percentile(arr,25))#0.25*3=0.75 (47-44)*0.75 = 2.25 2.25+44 = 46.25
print(np.percentile(arr,80))#0.8*3=2.4 (67-64)*(2.4-2)+64 = 65.2

2.0
2.5
[44 47 64 67]
55.5
46.25
65.2


In [129]:
# 累积和、累积积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


## 比较函数

比较是否大于、小于、等于
逻辑于、或、非
检查数组中是否有一个True,是否所有的都为True,自定义条件

In [135]:
# 是否大于
print(np.greater([3,4,5,6,7],4))
#是否小于
print(np.less([3,4,5,6,7],4))
#是否等于
print(np.equal([3,4,5,6,7],4))
print(np.equal([3,4,5],[4,4,4]))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False  True False]


In [139]:
#逻辑与
print(np.logical_and([0,0],[1,1]))
#逻辑或
print(np.logical_or([0,0],[1,0]))
#逻辑非
print(np.logical_not([0,1]))

[False False]
[ True False]
[ True False]


In [142]:
#检查元素是否至少有一个元素为True
print(np.any([0,0,0,0,0]))
#检查元素是否全部有一个元素为True
print(np.all([1,1,1,0,0]))

False
False


In [145]:
#自定义条件
#print(np.where(条件,符合条件,不符合条件的))
arr = np.array([1,2,3,4,5,6])
print(np.where(arr>3,arr,0))
print(np.where(arr<3,arr,0))

[0 0 0 4 5 6]
[1 2 0 0 0 0]


In [147]:
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,1,0))

[1 1 0 0 0]


In [149]:
score = np.random.randint(50,100,20)
print(score)
print(np.where(score>60,'及格','不及格'))

[63 58 59 70 66 55 65 97 50 68 85 74 99 79 69 69 64 89 82 51]
['及格' '不及格' '不及格' '及格' '及格' '不及格' '及格' '及格' '不及格' '及格' '及格' '及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '不及格']


In [151]:
print(np.where(
    score<60,'不及格',np.where(
        score<80,'良好','优秀'
    )
))

['良好' '不及格' '不及格' '良好' '良好' '不及格' '良好' '优秀' '不及格' '良好' '优秀' '良好' '优秀' '良好'
 '良好' '良好' '良好' '优秀' '优秀' '不及格']


In [155]:
#np.select(条件，返回的结果)
print(np.select([score>80,(score>=60) & (score<=80),score<60],
                ['优秀','良好','不及格'],
                default='未知'))

['良好' '不及格' '不及格' '良好' '良好' '不及格' '良好' '优秀' '不及格' '良好' '优秀' '良好' '优秀' '良好'
 '良好' '良好' '良好' '优秀' '优秀' '不及格']


In [25]:
# 排序函数
arr = np.random.randint(1,100,20)
print(arr)
#arr.sort()改变原始数组排序
#print(arr)
print(np.sort(arr))#不改变原始数组排序
print(np.argsort(arr))#查看索引
print(arr)

[81 95 29  4 18 31 93  3 59 52 93 70 82 55 82 32  2 53 16 28]
[ 2  3  4 16 18 28 29 31 32 52 53 55 59 70 81 82 82 93 93 95]
[16  7  3 18  4 19  2  5 15  9 17 13  8 11  0 12 14 10  6  1]
[81 95 29  4 18 31 93  3 59 52 93 70 82 55 82 32  2 53 16 28]


In [169]:
#去重函数
print(np.unique(arr))

[ 4 10 11 24 28 30 32 36 40 42 46 47 51 68 72 74 91]


In [172]:
#数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [177]:
#数组的分割
print(np.split(arr,4))#要整除才能切割
print(np.split(arr,[6,12,18]))#选定位置切割（切割位置的索引值）

[array([30, 68, 36, 40, 10], dtype=int32), array([74, 42, 24,  4, 47], dtype=int32), array([91, 51,  4, 32, 10], dtype=int32), array([11, 28, 46, 72, 40], dtype=int32)]
[array([30, 68, 36, 40, 10, 74], dtype=int32), array([42, 24,  4, 47, 91, 51], dtype=int32), array([ 4, 32, 10, 11, 28, 46], dtype=int32), array([72, 40], dtype=int32)]


In [26]:
#调整数组形状
print(np.reshape(arr,[4,5]))#需要能等分

[[81 95 29  4 18]
 [31 93  3 59 52]
 [93 70 82 55 82]
 [32  2 53 16 28]]


# 第2章 NumPy科学计算综合练习

In [27]:
arr = np.array([28,30,29,31,32,30,29])
average = np.mean(arr)
highest = np.max(arr)
lowest = np.min(arr)
daynum = len(arr[arr>30])
arr1 = np.greater(arr,30)
arr2 = np.where(arr>30,np.arange(arr.size),0)
print(arr)
print("平均值：%.3f"%average)
print("最大值：",highest)
print("最小值：",lowest)
print("列表中大于30的天数",arr1,arr2,daynum)
print(np.cumsum(np.where(arr>30,1,0))[-1])
print(np.count_nonzero(arr>30))

[28 30 29 31 32 30 29]
平均值：29.857
最大值： 32
最小值： 28
列表中大于30的天数 [False False False  True  True False False] [0 0 0 3 4 0 0] 2
2
2


In [39]:
mark = np.array([85,90,78,92,88])
average = np.mean(mark)
medi = np.median(mark)
std = np.std(mark)
tenscore = mark / 10
print("平均分为：",average)
print("中位数为：",medi)
print("标准差为：",std)
print("10分制下：",tenscore)

平均分为： 86.6
中位数为： 88.0
标准差为： 4.882622246293481
10分制下： [8.5 9.  7.8 9.2 8.8]


In [42]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("A+B:",A+B)
print("A*B:",A*B)
print("A@B:",A@B)
print("A@B:",np.dot(A,B))

A+B: [[ 6  8]
 [10 12]]
A*B: [[ 5 12]
 [21 32]]
A@B: [[19 22]
 [43 50]]
A@B: [[19 22]
 [43 50]]


In [65]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4),dtype = int)
print(arr)
for i in range(4):
    print("每列的最大值为：",np.max(arr[:,i]))
print('每列的最大值',np.max(arr,axis=0))#axis=0列 =1行
for i in range(3):
    print("每行的最小值为：",np.min(arr[i,:]))
print('每行最小值',np.min(arr,axis=1))
arr1 = np.where((arr%2==1),-1,arr)
print(arr1)
arr[arr%2==1]=-1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值为： 7
每列的最大值为： 9
每列的最大值为： 7
每列的最大值为： 6
每列的最大值 [7 9 7 6]
每行的最小值为： 0
每行的最小值为： 3
每行的最小值为： 2
每行最小值 [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [90]:
#arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype=int)
arr = np.arange(1,13)
print(arr)
arr = np.reshape(arr,(3,4))
print(arr)
average_x = np.sum(arr,axis=1)
print(average_x)
average_y = np.mean(arr,axis=0)
print(average_y)
arr = np.reshape(arr,(12))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [103]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10,0,arr))
print(arr)
arr[arr>10]=0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]
[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [108]:
arr = np.array([120,135,110,125,130,140])
sum = np.sum(arr)
mean = np.mean(arr)
var = np.var(arr)
print("总和为：",sum)
print("平均值：",mean)
print("方差：",var)
print("最高的月份:",np.argmax(arr)+1)
print("最低的月份:",np.argmin(arr)+1)

总和为： 760
平均值： 126.66666666666667
方差： 97.22222222222223
最高的月份: 6
最低的月份: 3


In [114]:
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate((A,B))
print(C)
print(np.reshape(C,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [123]:
arr = np.array([2,1,2,3,1,4,3])
print(np.unique(arr))
u_arr,counts = np.unique(arr,return_counts = True)
print(u_arr,counts)
d = []
for i in range(len(u_arr)):
    d= d + [len(arr[arr == u_arr[i]])]
print(d)

[1 2 3 4]
[1 2 3 4] [2 2 2 1]
[2, 2, 2, 1]


In [129]:
sale = np.array([20,25,22,30,28])
cost = np.array([15,18,16,22,20])
profit = sale - cost
print(profit)
print(np.mean(profit))
print(np.std(profit))
print(len(profit[profit == np.max(profit)]))

[5 7 6 8 8]
6.8
1.16619037896906
2
